spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    username: testUser
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    password: ''


